### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by sefinek24** [4lex4nder/ReshadeEffectShaderToggler#19]
The new version (v.1.2.3) causes higher RAM usage in the game. Without this add-on, the game only use 3 GB, but with this add-on, it goes over 10 GB. When the memory runs out, the game crashes.

Any solutions?

**Comment by sefinek24** [comment]
In version v1.2.2, this issue does not exist.

**Comment by 4lex4nder** [comment]
What game is this? 1.2.3 only added an about dialogue, not sure how this could cause something like this.

**Comment by sefinek24** [comment]
> What game is this? 1.2.3 only added an about dialogue, not sure how this could cause something like this.

https://genshin.hoyoverse.com/en/

**Comment by sefinek24** [comment]
It will be fixed? My bad, in version v1.2.2 this error too exists

**Comment by sefinek24** [comment]
@4lex4nder

**Comment by 4lex4nder** [comment]
Should be fixed by 0ef74f1

**Comment by sefinek24** [comment]
Broo @4lex4nder

**Comment by sefinek24** [comment]
Ooo thanks i'll check

**Comment by sefinek24** [comment]
Fixed. Thanks
