### ISSUE TITLE
Upside down in/output at specific toggle group

### ISSUE THREAD

**Issue by Small-Ku** [4lex4nder/ReshadeEffectShaderToggler#23]
![iMMERSE launchpad debug output](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/16464896/47b7bb92-3c24-4a26-8da0-9420288e605f)
Can the addon deal with this like upside down the input and output of shaders?

**Comment by 4lex4nder** [comment]
This should be fixed by setting RESHADE_DEPTH_INPUT_IS_UPSIDE_DOWN to 1, I think. REST itself does not intervene in how the game applies it's own shaders.

**Comment by Small-Ku** [comment]
But it only upside down inside some shaders of the game.

**Comment by logarrhythmic** [comment]
I have a similar problem with that other anime game from this developer, my RESHADE_DEPTH_INPUT_IS_UPSIDE_DOWN is set to 1 and it fixes the depth buffer for shaders, but there are a lot of shaders in the group settings that show the preview upside-down and using them will make affected shaders also flip upside down. For example, I have one pixel shader where the preview is exactly the 3D scene without the UI, but it's upside down. If I select it and set `Invocation location` to `AFTER DRAW` or `ON RENDER TARGET CHANGE`, the UI is perfectly excluded and right-side-up, but anything ReShade touches is flipped upside down.
![image](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/1952758/702bff77-b787-4d54-a698-3a90ac0bb03c)
There are some other pixel shaders that seem to contain most of the UI and don't flip anything.
![image](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/1952758/d345c589-2ad5-41bc-ac16-706accad15e2)
The NPC nameplate is not excluded properly here. 
It would be nice to have some kind of upside-down toggle somewhere, but I don't actually know how any of this works, so maybe there's already something I could do if I knew how.

**Comment by carycary246** [comment]
Same issue with Genshin as well. Some shaders are flipped such as this one for fog which breaks when I want to use that toggle group so I can use MXAO and RTGI without applying to the fog as otherwise they will show through. However, as you can see it is flipped so it renders upside down so we need a switch for this toggle group to flip it.
![upside down shader](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/31323333/d4291c83-8f82-4234-97ad-194857fd9176)

**Comment by 4lex4nder** [comment]
Added option to flip with 1.3.8

**Comment by carycary246** [comment]
> Added option to flip with 1.3.8
Thanks for adding this but running into an issue with flipping, it doesn't do the full image. I suspect it may be related to my game resolution being 2560x1440 but the addon is reporting 3840x2160 resulting in a mismatched flip.

![image](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/31323333/fcd386f4-60ca-439d-a947-66228cb27b27)

**Comment by 4lex4nder** [comment]
If you're using FSR2/DLSS with scaling factor != 1.0: Don't

**Comment by KuroZantetsuken** [comment]
I don't know if my assumptions are incorrect, but "Flip render target" doesn't do anything for me in a different flavour of the anime games (ZZZ). I'm manually injecting ReShade 6.5.1 and using REST 1.3.23.633.

https://github.com/user-attachments/assets/3224e554-3565-4fbd-86ac-a91aa0730e9e
