### ISSUE TITLE
Blinking screen while rotating the camera

### ISSUE THREAD

**Issue by sefinek24** [4lex4nder/ReshadeEffectShaderToggler#32]
When rotating the camera, the image starts to flicker. This issue did not occur in version 1.2.7.
Below, I have provided a link to the recording.

https://youtu.be/4I9pbihHuTY

**Comment by sefinek24** [comment]
@4lex4nder

**Comment by Stereo-3D** [comment]
This blinking issue also happened to me too, here is my video showing the flicker: https://youtu.be/ZlzUMyBssbU

I've contacted Alex on discord a week ago about this issue and understand that he is busy so it may take a while :crossed_fingers:

**Comment by 4lex4nder** [comment]
Fixed: d8107f40b6b7551481482f84a8a659d1cb2b801e
