### ISSUE TITLE
ReShade reloads from time to time

### ISSUE THREAD

**Issue by sefinek24** [4lex4nder/ReshadeEffectShaderToggler#38]
In the new version, I encounter 'reshade reloading' once again.

Video:
https://cdn.discordapp.com/attachments/1044713077125435495/1162282590556930078/2023-10-13_14-50-35_1.mp4

**Comment by 4lex4nder** [comment]
This happens when the render target of the shader you assigned to a group don't have the same format as the swapchain. So if a group is not matched, it will render those effects onto the back buffer, which, if it has a different format, forces ReShade to reload all effects. One could of course *not* render any effects in such a case, but that'd be equally jarring. Not much I can do about this, unfortunately.

**Comment by sefinek24** [comment]
In the previous version, it worked normally.

**Comment by 4lex4nder** [comment]
Previous as in 1.3.3?

**Comment by sefinek24** [comment]
After the fix from #32, I didn't have any problems with that addon

**Comment by sefinek24** [comment]
I've checked it thoroughly, and versions higher than v1.2.7 indeed have this issue, and a few others on top of that.

**Comment by 4lex4nder** [comment]
What config are you using?

**Comment by sefinek24** [comment]
I don't want to send it here. Can you give me your email?

**Comment by 4lex4nder** [comment]
Or rather, does the following config have the same issue?
```
[General]
ResourceShim=none
ConstantBufferHookType=none
ConstantBufferHookCopyType=singular
TrackDescriptors=True
AmountGroups=1

[Keybindings]
PIXEL_SHADER_DOWN=97
PIXEL_SHADER_UP=98
PIXEL_SHADER_MARK=99
PIXEL_SHADER_MARKED_DOWN=4449
PIXEL_SHADER_MARKED_UP=4450
VERTEX_SHADER_DOWN=100
VERTEX_SHADER_UP=101
VERTEX_SHADER_MARK=102
VERTEX_SHADER_MARKED_DOWN=4452
VERTEX_SHADER_MARKED_UP=4453
INVOCATION_DOWN=103
INVOCATION_UP=104
DESCRIPTOR_DOWN=109
DESCRIPTOR_UP=107

[Group0_VertexShaders]
AmountHashes=0

[Group0_PixelShaders]
ShaderHash0=2006665982
AmountHashes=1

[Group0_ComputeShaders]
AmountHashes=0

[Group0_Constants]
AmountConstants=0

[Group0]
Name=UI
ToggleKey=0
Active=True
RenderTargetIndex=0
InvocationLocation=0
MatchSwapchainResolutionOnly=0
RequeueAfterRTMatchingFailure=True
AllowAllTechniques=True
TechniqueExceptions=False
ProvideTextureBinding=False
TextureBindingName=BLAH
ClearTextureBindings=False
CopyTextureBinding=True
ExtractConstants=False
ConstantPipelineSlot=0
ConstantDescriptorIndex=0
ConstantPushMode=False
ConstantShaderStage=0
ExtractSRVs=False
SRVPipelineSlot=0
SRVDescriptorIndex=0
SRVShaderStage=0
BindingRenderTargetIndex=0
BindingInvocationLocation=0
BindingMatchSwapchainResolutionOnly=0
ClearPreviewAlpha=True
```

**Comment by sefinek24** [comment]
I'll check

**Comment by 4lex4nder** [comment]
Or alternatively this one:
```
[General]
ResourceShim=none
ConstantBufferHookType=none
ConstantBufferHookCopyType=singular
TrackDescriptors=True
AmountGroups=1

[Keybindings]
PIXEL_SHADER_DOWN=97
PIXEL_SHADER_UP=98
PIXEL_SHADER_MARK=99
PIXEL_SHADER_MARKED_DOWN=4449
PIXEL_SHADER_MARKED_UP=4450
VERTEX_SHADER_DOWN=100
VERTEX_SHADER_UP=101
VERTEX_SHADER_MARK=102
VERTEX_SHADER_MARKED_DOWN=4452
VERTEX_SHADER_MARKED_UP=4453
INVOCATION_DOWN=103
INVOCATION_UP=104
DESCRIPTOR_DOWN=109
DESCRIPTOR_UP=107

[Group0_VertexShaders]
AmountHashes=0

[Group0_PixelShaders]
ShaderHash0=445598465
AmountHashes=1

[Group0_ComputeShaders]
AmountHashes=0

[Group0_Constants]
AmountConstants=0

[Group0]
Name=UI
ToggleKey=0
Active=True
RenderTargetIndex=0
InvocationLocation=2
MatchSwapchainResolutionOnly=0
RequeueAfterRTMatchingFailure=True
AllowAllTechniques=True
TechniqueExceptions=False
ProvideTextureBinding=False
TextureBindingName=BLAH
ClearTextureBindings=False
CopyTextureBinding=True
ExtractConstants=False
ConstantPipelineSlot=0
ConstantDescriptorIndex=0
ConstantPushMode=False
ConstantShaderStage=0
ExtractSRVs=False
SRVPipelineSlot=0
SRVDescriptorIndex=0
SRVShaderStage=0
BindingRenderTargetIndex=0
BindingInvocationLocation=0
BindingMatchSwapchainResolutionOnly=0
ClearPreviewAlpha=True
```

Both work fine on my end, with this one being slightly better since it also account for menu backgrounds

**Comment by sefinek24** [comment]
0 changes

ReShade:
![2023-10-14 17-24-52](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/92880265/b507f953-865b-4426-b460-f530ba5e781d)

Without reshade:
![2023-10-14 17-24-52 original](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/92880265/cd6a8353-0a63-4f13-94f3-c89a825a71a4)

**Comment by sefinek24** [comment]
![Untitled](https://github.com/4lex4nder/ReshadeEffectShaderToggler/assets/92880265/c51b4af5-a118-43e1-b6ed-7cc3f0a35734)

**Comment by sefinek24** [comment]
bugged: https://youtu.be/KD1Ilv-RiuY

**Comment by 4lex4nder** [comment]
Hmm, alright, will need to dig a bit

**Comment by 4lex4nder** [comment]
Try 1.3.4

**Comment by sefinek24** [comment]
Thanks, the issue with ReShade reloads has been resolved, however, there are currently two other errors:

1. Flickering ReShade filters while scrolling through items in the craft bench.
2. Black screen when configuring the add-on in the craft bench interface.

Video: https://youtu.be/viLBrDvn65g

**Comment by 4lex4nder** [comment]
1. Doesn't seem to be a regression, same issue with 1.2.7. Seems to be just the game doing something goofy
2. Looks like something is wrong with the alpha clearing shader. For now you can disable `Clear alpha channel` in the preview window

**Comment by sefinek24** [comment]
It seems like the issues have been resolved. If anything comes up, I'll create a new Issue. Thanks.
