### ISSUE TITLE
Anno 1800 DX12 StateTracking.cpp:475 access out of bounds

### ISSUE THREAD

**Issue by sqwishy** [4lex4nder/ReshadeEffectShaderToggler#40]
Tested on 6e7b17e.

After the main menu and loading screen, as the 3D world begins to show up, an out of bounds access occurs on [StateTracking.cpp:475](https://github.com/4lex4nder/ReshadeEffectShaderToggler/blob/6e7b17e/src/StateTracking.cpp#L475)

    auto& buf = descriptor_buffer[root_table_entry.buffer_index];
 
- `root_table_entry.buffer_index` is `-1`
- `root_table_entry.type` is `root_entry_type::descriptor_table`

I thought maybe root_table (`std::vector<root_entry>`) would be parallel to
params (`std::vector<reshade::api::pipeline_layout_param>`). The elements didn't seem to match up? But I could be totally misreading this. I don't really know what I'm doing here or anything about graphics. I figured it was worth asking in case you have any ideas.

**Comment by 4lex4nder** [comment]
Current version requires a git build of ReShade for the DX12 state tracking changes to work. At least until a new official ReShade version is released.

**Comment by sqwishy** [comment]
Oh yeah, I built ReShade and tested again and it seems stable!

By the way, I don't remember being able to select the shaders from a list under toggle group settings dialog. Maybe it's new in the last few months? It's a big improvement over cycling and marking with the numpad. Very cool addon!
