### ISSUE TITLE
Guild Wars 2 Crash v1.3.15

### ISSUE THREAD

**Issue by XIIICaesar** [4lex4nder/ReshadeEffectShaderToggler#57]
Hi. Recently updated ReShade to v6.0.1 & noticed REST in the addon downloads during installation. I thought 'cool I've been using the outdated version from a year ago I found on Reddit' & so I downloaded your version. Upon exiting the game I got an error message but they don't give any specific info with it. Searched for a crash log but no luck there either. Used my old version & no error. Used your v1.3.15 & v1.3.14(x64 version) even renamed the file ReshadeEffefctShaderToggler.addon (same name as original) instead of ReshadeEffectShaderToggler.addon64 & still crash error after exiting the game. When I tried v1.3.13 though it work right out the box, ReshadeEffectShaderToggler.addon64. I know that's not much to go on but that's the issue. v1.3.13 works while v1.3.14/15 error after exiting.

**Comment by Lennn888** [comment]
REST configs are version dependent to some extent: if your config is too old (=made with early REST version), it won't work with most recent versions.

Here is an updated config for Guild Wars 2, just change file extension as github doesn't let me upload .ini here.

[ReshadeEffectShaderToggler.txt](https://github.com/4lex4nder/ReshadeEffectShaderToggler/files/14662155/ReshadeEffectShaderToggler.txt)

**Comment by XIIICaesar** [comment]
So far that fixed it. Using v1.3.15 too.

**Comment by XIIICaesar** [comment]
Can I mark this as completed?
