### ISSUE TITLE
FilmGrain.fx freezes when REST enabled.

### ISSUE THREAD

**Issue by FoGsesipod** [4lex4nder/ReshadeEffectShaderToggler#6]
Title, not too sure how reproduceable this one is or if its attached to certain pixel or vertex shaders (I do not have any vertex shaders toggled however)

FilmGrain.fx set to disgusting values for easily display of bug
https://user-images.githubusercontent.com/104705517/218602934-fae6ff5c-e316-4435-bff9-bb7182b3adff.mp4

In fact it seems all film grain shaders do not work...

**Comment by 4lex4nder** [comment]
This was an issue with the initial 1.0.0 release or so, since it wouldn't update ReShade's inbuilt variables (like frametime), which this shader is using. Can you try the 1.1.0 pre-release?

**Comment by FoGsesipod** [comment]
Oh I didn't see the pre-release! Yes it seems that one fixes it.
